import { Injectable } from '@angular/core';

// Wompi Widget Interface
declare var WidgetCheckout: any;

@Injectable({
  providedIn: 'root'
})
export class WompiService {

  constructor() {}

  /**
   * Opens the Wompi WidgetCheckout with the provided data generated by the backend.
   */
  openWidget(paymentData: {
    reference: string;
    amountInCents: number;
    currency: string;
    signature: string;
    publicKey: string;
  }): Promise<any> {
    return new Promise((resolve, reject) => {
      try {
        if (typeof WidgetCheckout === 'undefined') {
          return reject(new Error('Wompi script not loaded.'));
        }

        const checkout = new WidgetCheckout({
          currency: paymentData.currency,
          amountInCents: paymentData.amountInCents,
          reference: paymentData.reference,
          publicKey: paymentData.publicKey,
          signature: { integrity: paymentData.signature }
        });

        checkout.open((result: any) => {
          const transaction = result.transaction;
          
          if (transaction.status === 'APPROVED') {
            resolve(transaction);
          } else if (transaction.status === 'DECLINED') {
            reject(new Error('Pago rechazado. Por favor intenta con otro medio de pago.'));
          } else if (transaction.status === 'ERROR') {
             reject(new Error('Ha ocurrido un error durante la transacción.'));
          } else {
             // PENDING o cualquier otro estado
             resolve(transaction);
          }
        });
      } catch (error) {
         console.error('Error opening Wompi Widget:', error);
         reject(error);
      }
    });
  }
}
